### ISSUE TITLE
vuex是从哪里引入的？

### ISSUE THREAD

**Issue by MontageD** [QinZhen001/didi#3]
在代码里面怎么找不到vuex引入的地方，但是你又能调用vuex 相关的方法？

**Comment by QinZhen001** [comment]
在main.js下

import Vue from 'vue'
import App from './index'
import store from '../../store/index'

Vue.prototype.$store = store

const app = new Vue(App)
app.$mount()

**Comment by MontageD** [comment]
好的，感谢🙏。
还有个小问题，就是使用你在开发的时候不知道有没碰到过使用Module引入的时候会让整个项目报错的情况。

**Comment by QinZhen001** [comment]
目前还没遇到过这个情况

**Comment by MontageD** [comment]
噢哦，好的，谢谢。
